### ISSUE TITLE
GridPane.get{Row,Column}Index ends in infinite loop

### ISSUE THREAD

**Issue by pilhuhn** [jruby/jrubyfx#103]
Take this code

    l = label 'Hello Label'
    @the_grid.add l, 1,2

    puts @the_grid.getRowIndex l

This will not print the index, but end up with

```
#<RuntimeError: Whoa! method_missing caught infinite loop. Trying to run getRowIndex([#<Java::JavafxSceneControl::Label:0x22d22f8b>]) failed. Method not found.>
/Users/hrupp/.rvm/gems/jruby-9.1.0.0/gems/jrubyfx-1.1.1-java/lib/jrubyfx/dsl.rb:101:in `method_missing'
/Users/hrupp/.rvm/gems/jruby-9.1.0.0/gems/jrubyfx-1.1.1-java/lib/jrubyfx/core_ext/precompiled.rb:1809:in `method_missing'
/Users/hrupp/.rvm/gems/jruby-9.1.0.0/gems/jrubyfx-1.1.1-java/lib/jrubyfx/dsl.rb:103:in `method_missing'
/Users/hrupp/.rvm/gems/jruby-9.1.0.0/gems/jrubyfx-1.1.1-java/lib/jrubyfx/core_ext/precompiled.rb:1809:in `method_missing'
/Users/hrupp/.rvm/gems/jruby-9.1.0.0/gems/jrubyfx-1.1.1-java/lib/jrubyfx/dsl.rb:103:in `method_missing'
/Users/hrupp/.rvm/gems/jruby-9.1.0.0/gems/jrubyfx-1.1.1-java/lib/jrubyfx/core_ext/precompiled.rb:1809:in `method_missing'
/Users/hrupp/.rvm/gems/jruby-9.1.0.0/gems/jrubyfx-1.1.1-java/lib/jrubyfx/dsl.rb:103:in `method_missing'
/devel/jrubyfx/samples/fxml/Demo.rb:108:in `initialize'
```

With Demo.rb:108 being the 'puts' line from above. The `@the_grid` is the GridPane from the Demo app

**Comment by byteit101** [comment]
Yes, GridPane::getRowIndex is a static, not instance, method

https://docs.oracle.com/javase/8/javafx/api/javafx/scene/layout/GridPane.html#getRowIndex-javafx.scene.Node-

`puts GridPane::getRowIndex(l)`

**Comment by pilhuhn** [comment]
Stupid me - sorry for the noise
