### ISSUE TITLE
Setting TableView items doesn't seem to work

### ISSUE THREAD

**Issue by monkeysuffrage** [jruby/jrubyfx#113]
The table sample code here: https://github.com/jruby/jrubyfx/blob/master/samples/javafx/table_app.rb
doesn't seem to set the data properly.
Is there a working example of setting table data in TableView?

**Comment by byteit101** [comment]
You need to create a cellfactory to display data. This sample should work:

https://github.com/jruby/jrubyfx/blob/master/samples/contrib/fxmltableview/

specifically https://github.com/jruby/jrubyfx/blob/master/samples/contrib/fxmltableview/FormattedTableCellFactory.rb

**Comment by monkeysuffrage** [comment]
Thanks byteit101,
That link was helpful. Does that code work for you? When I run it I get:

jruby FXMLTableView.rb
C:/jruby-9.1.12.0/lib/ruby/gems/shared/gems/jrubyfx-fxmlloader-0.4.1-java/lib/fxmlloader/elts.rb:158: warning: `<<' after local variable or literal is interpreted as binary operator
C:/jruby-9.1.12.0/lib/ruby/gems/shared/gems/jrubyfx-fxmlloader-0.4.1-java/lib/fxmlloader/elts.rb:158: warning: even though it seems like here document
saved C:/Cygwin/home/owner/ruby/jrubyfx/samples/contrib/fxmltableview/.jrubyfx_cache/a3f32098b1a72785e7d4ee9188a7ca1cb657c1d6.rb to cache
Exception in thread "JavaFX Application Thread" java.lang.AbstractMethodError: rubyobj.FormattedTableCellFactory.call(Ljava/lang/Object;)Ljava/lang/Object;
	at com.sun.javafx.scene.control.skin.TableRowSkin.getCell(com/sun/javafx/scene/control/skin/TableRowSkin.java:87)
	at com.sun.javafx.scene.control.skin.TableRowSkin.getCell(com/sun/javafx/scene/control/skin/TableRowSkin.java:53)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.createCell(com/sun/javafx/scene/control/skin/TableRowSkinBase.java:698)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.recreateCells(com/sun/javafx/scene/control/skin/TableRowSkinBase.java:692)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.init(com/sun/javafx/scene/control/skin/TableRowSkinBase.java:146)
	at com.sun.javafx.scene.control.skin.TableRowSkin.<init>(com/sun/javafx/scene/control/skin/TableRowSkin.java:64)
	at javafx.scene.control.TableRow.createDefaultSkin(javafx/scene/control/TableRow.java:212)
	at javafx.scene.control.Control.impl_processCSS(javafx/scene/control/Control.java:872)
	at javafx.scene.Node.processCSS(javafx/scene/Node.java:9058)
	at javafx.scene.Node.applyCss(javafx/scene/Node.java:9155)
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(com/sun/javafx/scene/control/skin/VirtualFlow.java:1964)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCell(com/sun/javafx/scene/control/skin/VirtualFlow.java:1797)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getCellLength(com/sun/javafx/scene/control/skin/VirtualFlow.java:1879)
	at com.sun.javafx.scene.control.skin.VirtualFlow.computeViewportOffset(com/sun/javafx/scene/control/skin/VirtualFlow.java:2528)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(com/sun/javafx/scene/control/skin/VirtualFlow.java:1189)
	at javafx.scene.Parent.layout(javafx/scene/Parent.java:1087)
	at javafx.scene.Parent.layout(javafx/scene/Parent.java:1093)
	at javafx.scene.Parent.layout(javafx/scene/Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(javafx/scene/Scene.java:552)
	at javafx.scene.Scene.preferredSize(javafx/scene/Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(javafx/scene/Scene.java:1720)
	at javafx.stage.Window$9.invalidated(javafx/stage/Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(javafx/beans/property/BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(javafx/beans/property/BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(javafx/stage/Window.java:922)
	at javafx.stage.Window.show(javafx/stage/Window.java:937)
	at javafx.stage.Stage.show(javafx/stage/Stage.java:259)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:438)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:302)
	at FXMLTableView.invokeOther11:show(FXMLTableView.rb:46)
	at FXMLTableView.start(FXMLTableView.rb:46)
	at RUBY.block in launch_app_after_platform(C:/jruby-9.1.12.0/lib/ruby/gems/shared/gems/jrubyfx-1.2.0-java/lib/jrubyfx/java_fx_impl.rb:119)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:246)
	at org.jruby.javasupport.Java$ProcToInterface.callProc(org/jruby/javasupport/Java.java:1112)
	at org.jruby.javasupport.Java$ProcToInterface.access$300(org/jruby/javasupport/Java.java:1089)
	at org.jruby.javasupport.Java$ProcToInterface$ConcreteMethod.call(org/jruby/javasupport/Java.java:1150)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(com/sun/javafx/application/PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(com/sun/javafx/application/PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(com/sun/javafx/application/PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(com/sun/glass/ui/InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(com/sun/glass/ui/win/WinApplication.java:191)
	at java.lang.Thread.run(java/lang/Thread.java:748)
Exception in thread "JavaFX Application Thread" java.lang.AbstractMethodError: rubyobj.FormattedTableCellFactory.call(Ljava/lang/Object;)Ljava/lang/Object;
	at com.sun.javafx.scene.control.skin.TableRowSkin.getCell(TableRowSkin.java:87)
	at com.sun.javafx.scene.control.skin.TableRowSkin.getCell(TableRowSkin.java:53)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.createCell(TableRowSkinBase.java:698)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.recreateCells(TableRowSkinBase.java:692)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.init(TableRowSkinBase.java:146)
	at com.sun.javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:64)
	at javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:212)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "JavaFX Application Thread" java.lang.AbstractMethodError: rubyobj.FormattedTableCellFactory.call(Ljava/lang/Object;)Ljava/lang/Object;
	at com.sun.javafx.scene.control.skin.TableRowSkin.getCell(TableRowSkin.java:87)
	at com.sun.javafx.scene.control.skin.TableRowSkin.getCell(TableRowSkin.java:53)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.createCell(TableRowSkinBase.java:698)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.recreateCells(TableRowSkinBase.java:692)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.init(TableRowSkinBase.java:146)
	at com.sun.javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:64)
	at javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:212)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)

Then it saves something in .jrubyfx_cache and when I run it again it launches but there's no data in the table. It looks like there's supposed to be 5 people in the table but the data is empty. I can add people with the add button so that's something.

owner@PC ~/ruby/jrubyfx/samples/contrib/fxmltableview: jruby -v
jruby 9.1.12.0 (2.3.3) 2017-06-15 33c6439 Java HotSpot(TM) 64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [mswin32-x86_64]

owner@PC ~/ruby/jrubyfx/samples/contrib/fxmltableview: jruby -S gem list | grep jruby
jruby-openssl (default: 0.9.20 java)
jruby-readline (default: 1.1.1 java)
jruby-win32ole (0.8.5)
jrubyfx (1.2.0 java)
jrubyfx-fxmlloader (0.4.1 java)

**Comment by byteit101** [comment]
@enebo: this sample is a great example of jruby reification failing in 9000 series with a `java.lang.AbstractMethodError` where it works in 1.7

1.7.19 works just fine for me though

**Comment by monkeysuffrage** [comment]
Thanks for that, 1.7 is working for me too.
