### ISSUE TITLE
jrubfx-jarify compiled jar does not laucnch

### ISSUE THREAD

**Issue by sotrhRaven** [jruby/jrubyfx#118]
jdk8
jruby 9.1.15.0

java -jar v2t.jar
uri:classloader:/fxmlloader/elts.rb:158: warning: `<<' after local variable or literal is interpreted as binary operator
uri:classloader:/fxmlloader/elts.rb:158: warning: even though it seems like here document
Exception running Application:
#<Errno::ENOTDIR: Not a directory - classpath:/.jrubyfx_cache>
org/jruby/RubyDir.java:449:in `mkdir'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:253:in `fu_mkdir'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:227:in `block in mkdir_p'
org/jruby/RubyArray.java:1819:in `reverse_each'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:225:in `block in mkdir_p'
org/jruby/RubyArray.java:1735:in `each'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:211:in `mkdir_p'
uri:classloader:/fxmlloader/fxml_jit_info.rb:64:in `initialize'
uri:classloader:/jrubyfx-fxmlloader.rb:294:in `load'
uri:classloader:/jrubyfx/controller.rb:129:in `load_into'
uri:classloader:/jrubyfx/core_ext/stage.rb:82:in `fxml'
classpath:/jar-bootstrap.rb:7:in `block in start'
org/jruby/RubyBasicObject.java:1691:in `instance_eval'
uri:classloader:/jrubyfx/module.rb:49:in `with'
classpath:/jar-bootstrap.rb:6:in `start'
uri:classloader:/jrubyfx/java_fx_impl.rb:119:in `block in launch_app_after_platform'

**Comment by Dr-Chaos** [comment]
+1 same issue

**Comment by justinsoong** [comment]
Errno::ENOTDIR: Not a directory - classpath:/.jrubyfx_cache seems to be the issue here, I tried to use this workaround https://github.com/jruby/jrubyfx/issues/115

But didn't help, it copied the folder to the staging directory, but possibly not picked up on compile

**Comment by justinsoong** [comment]
The wildcard doesn't pick up the .jrubyfx_cache folder

```
jar ufe 'kiosk.jar' org.jruby.JarBootstrapMain *
```

**Comment by enebo** [comment]
@justinsoong if you change the jar command does this work?  I am trying to understand whether this is actually an issue with JRuby (regression) or JRubyFX itself?

**Comment by bolandross** [comment]
+1 same issue
