### ISSUE TITLE
setHgrow missing for HBox

### ISSUE THREAD

**Issue by blerins** [jruby/jrubyfx#97]
Trying to invoque setHgrow for HBox fails:

```JRuby
    def start(main_stage)
      layout = hbox
      lab = label
      layout.children.add_all(lab)
      layout.setHgrow(lab, javafx.scene.layout.Priority::ALWAYS)
      #[....]
    end
```

```
uri:classloader:/jruby/kernel/kernel.rb:17: warning: unsupported exec option: close_others
Exception running Application:
#<NoMethodError: undefined method `setHgrow' for #<Java::JavafxSceneLayout::HBox:0x46e44e8 @supers={:setHgrow=>1}>>
org/jruby/RubyBasicObject.java:1592:in `method_missing'
/home/bruno/.rbenv/versions/jruby-9.0.1.0/lib/ruby/gems/shared/gems/jrubyfx-1.1.1-java/lib/jrubyfx/dsl.rb:103:in `method_missing'
/home/bruno/.rbenv/versions/jruby-9.0.1.0/lib/ruby/gems/shared/gems/jrubyfx-1.1.1-java/lib/jrubyfx/core_ext/precompiled.rb:1685:in `method_missing'
/home/bruno/workspace/test.rb:22:in `start'
/home/bruno/.rbenv/versions/jruby-9.0.1.0/lib/ruby/gems/shared/gems/jrubyfx-1.1.1-java/lib/jrubyfx/java_fx_impl.rb:119:in `block in launch_app_after_platform'
```

Thanks

**Comment by oreoshake** [comment]
@blerins try `HBox.setHgrow(lab, javafx.scene.layout.Priority::ALWAYS)`

**Comment by byteit101** [comment]
yes, setHgrow is a static method: https://docs.oracle.com/javafx/2/api/javafx/scene/layout/HBox.html#setHgrow%28javafx.scene.Node,%20javafx.scene.layout.Priority%29 and we currently don't bother copying static methods into instances

**Comment by blerins** [comment]
D'oh! You are right, it's a static method. My bad...

Thanks a lot!
